[CmdletBinding()]
param()

$ErrorActionPreference = 'Stop'
$root = Split-Path -Parent $PSScriptRoot
Push-Location $root
try {
  $tracked = @(git ls-files)
  if ($LASTEXITCODE -ne 0) { throw 'Unable to enumerate tracked files.' }

  $forbidden = @($tracked | Where-Object {
    $_ -match '(^|/)(artifacts|dist|bin|obj|diagnostics|local-state|local-test-data)/' -or
    $_ -match '(^|/)scene-(smoke|isolate|pointer|ripple)-' -or
    $_ -match '\.(pfx|p12)$'
  })
  if ($forbidden.Count -gt 0) {
    throw "Forbidden generated or sensitive paths are tracked:`n$($forbidden -join "`n")"
  }

  # Media stays deny-by-default. Project-owned assets and documentation
  # screenshots may be admitted only after their origin and terms are recorded.
  $approvedMedia = @(
    'assets/CWS-logo-v3.0.png',
    'docs/images/showcase/controller-en.png',
    'docs/images/showcase/controller-zh.png',
    'docs/images/showcase/media-static-image.png',
    'docs/images/showcase/opacity-100.png',
    'docs/images/showcase/opacity-44.png',
    'docs/images/showcase/opacity-66.png',
    'docs/images/showcase/overview.png',
    'docs/images/showcase/style-bright-texture.png',
    'docs/images/showcase/style-high-saturation.png',
    'docs/images/showcase/style-soft-low-contrast.png',
    'docs/images/showcase/workspace-background.png',
    # Generated by scripts/build-promotion-assets.ps1 from the approved
    # project-owned logo and documentation screenshot above.
    'promotion/assets/bilibili-cover.jpg',
    'promotion/assets/compatibility-card.jpg',
    'promotion/assets/end-card.jpg',
    'promotion/assets/social-preview.jpg',
    'promotion/assets/vertical-cover.jpg'
  )
  $media = @($tracked | Where-Object { $_ -match '(?i)\.(png|jpe?g|gif|webp|mp4|webm|mov|avi)$' })
  $unreviewedMedia = @($media | Where-Object { $_ -notin $approvedMedia })
  if ($unreviewedMedia.Count -gt 0) {
    throw "Media files require explicit licensing review and are not accepted by the baseline policy:`n$($unreviewedMedia -join "`n")"
  }

  $large = foreach ($path in $tracked) {
    if (Test-Path -LiteralPath $path -PathType Leaf) {
      $item = Get-Item -LiteralPath $path
      if ($item.Length -gt 10MB) { $path }
    }
  }
  if (@($large).Count -gt 0) {
    throw "Tracked files exceed 10 MiB:`n$(@($large) -join "`n")"
  }

  $secretPattern = '(github' + '_pat_|gh[pousr]_[A-Za-z0-9_]{20,}|sk' + '-[A-Za-z0-9_-]{20,}|AIza[0-9A-Za-z_-]{20,}|BEGIN (RSA|OPENSSH|EC) PRIVATE KEY)'
  $privatePattern = '@(gmail|qq|outlook|hotmail|163|126)\.com|[A-Za-z]:\\Users\\[^\\/]+\\'
  foreach ($pattern in @($secretPattern, $privatePattern)) {
    $hits = @(& git grep -n -I -E $pattern -- . ':(exclude)scripts/repository-hygiene.ps1' 2>$null)
    if ($LASTEXITCODE -gt 1) { throw 'Repository content scan failed.' }
    if ($hits.Count -gt 0) {
      throw "Potential credential or personal-data pattern found. Review these locations before committing:`n$($hits -join "`n")"
    }
  }

  Write-Output "Repository hygiene: PASS ($($tracked.Count) tracked files, no forbidden paths, unreviewed media, large files, credentials, private emails, or user-profile paths)."
}
finally {
  Pop-Location
}

# `git grep` uses exit code 1 for a clean no-match result. Make the script's
# successful contract explicit for CI runners that preserve native exit codes.
exit 0
